COPY INTO "TEAM5"."RAW_DATA"."FLIGHT_DATA"
    FROM 's3://team5-s3/{parquet_file}'
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    STORAGE_INTEGRATION = TEAM5_S3_INTEGRATION
    FILE_FORMAT = (
    TYPE =PARQUET,
    REPLACE_INVALID_CHARACTERS= TRUE,
    BINARY_AS_TEXT= FALSE
    )
    ON_ERROR=ABORT_STATEMENT;